name: Claude Code Review (Read-Only)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-review:
    # Only trigger on @claude-review command from authorized users
    if: |
      (
        github.event_name == 'issue_comment' ||
        github.event_name == 'pull_request_review_comment'
      ) &&
      contains(github.event.comment.body, '@claude-review') &&
      contains(fromJSON('["Oliver-Sheaky"]'), github.event.comment.user.login)

    runs-on: ubuntu-latest

    permissions:
      contents: read # Read-only access
      pull-requests: write # Allow comments on PRs
      issues: write # Allow comments on issues
      actions: read # Read CI results
      id-token: write # Required for OIDC authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better context

      - name: Load review instructions
        id: load-instructions
        env:
          EVENT_NAME: ${{ github.event_name }}
          ISSUE_NUM: ${{ github.event.issue.number }}
          PR_NUM: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.repository }}
          TRIGGERED_BY: ${{ github.event.comment.user.login }}
        run: |
          # Get the PR number from the event
          if [ "$EVENT_NAME" == "issue_comment" ]; then
            PR_NUMBER="${ISSUE_NUM}"
          else
            PR_NUMBER="${PR_NUM}"
          fi

          # Read the review template
          INSTRUCTIONS=$(cat .github/prompts/docker_review_prompt.md)

          # Use heredoc to preserve multiline content with context prepended
          echo "CUSTOM_INSTRUCTIONS<<EOF" >> $GITHUB_OUTPUT
          echo "# GitHub Context" >> $GITHUB_OUTPUT
          echo "- Repository: ${REPO_NAME}" >> $GITHUB_OUTPUT
          echo "- PR Number: ${PR_NUMBER}" >> $GITHUB_OUTPUT
          echo "- Triggered by: ${TRIGGERED_BY}" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "$INSTRUCTIONS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Claude Code Review
        id: claude
        uses: anthropics/claude-code-action@beta
        timeout-minutes: 15
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Custom trigger phrase for review workflow
          trigger_phrase: "@claude-review"

          # Review-specific instructions loaded from template
          custom_instructions: ${{ steps.load-instructions.outputs.CUSTOM_INSTRUCTIONS }}

          # Docker/Infrastructure review tools (read-only)
          # Removed Python-specific test tools (pytest, mypy, ruff)
          # Added docker-compose config validation
          allowed_tools: "Read(*),Grep(*),LS(*),Glob(*),Bash(docker-compose config*),Bash(docker compose config*),Bash(MSYS_NO_PATHCONV=1 docker-compose config*),Bash(git log*),Bash(git diff*),Bash(git status*),Bash(git show*),Bash(cat *),Bash(head *),Bash(tail *),Bash(wc *),Bash(find * -type f),WebSearch(*)"

  unauthorized-message:
    # Post message for unauthorized users
    if: |
      (
        github.event_name == 'issue_comment' ||
        github.event_name == 'pull_request_review_comment'
      ) &&
      contains(github.event.comment.body, '@claude-review') &&
      !contains(fromJSON('["Oliver-Sheaky"]'), github.event.comment.user.login)

    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Post unauthorized message
        uses: actions/github-script@v7
        with:
          script: |
            const comment = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ @${context.actor} - You are not authorized to trigger Claude reviews.\n\nOnly the maintainers can trigger Claude: Please ask a maintainer for review.`
            };

            if (context.eventName === 'issue_comment') {
              await github.rest.issues.createComment({
                ...comment,
                issue_number: context.issue.number
              });
            } else if (context.eventName === 'pull_request_review_comment') {
              await github.rest.pulls.createReplyForReviewComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                comment_id: context.payload.comment.id,
                body: comment.body
              });
            }
