version: '2'

networks:
  codi-internal: {}

services:
  codimd:
    image: 'hackmdio/hackmd:${CODIMD_IMAGE_VERSION:-2.4.2-cjk}'
    depends_on:
      - 'codimd-db'
    environment:
      # https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-configuration
      CMD_DB_URL: 'postgres://codimd:mypwd@codimd-db/codimd'
      CMD_USECDN: 'false'
    healthcheck:
      test: ['CMD', 'wget', '0.0.0.0:3000']
    labels:
      traefik.enable: true
      traefik.http.routers.codimd.rule: 'Host(`codimd.${SITE:-localhost}`)'
      traefik.http.services.codimd.loadbalancer.server.port: 3000
    links:
      - 'codimd-db'
    networks:
      - 'codi-internal'
      - 'srv'
    restart: 'always'
    volumes:
      - './data:/home/hackmd/app/public/uploads'

  codimd-db:
    image: 'postgres:11.6-alpine'
    environment:
      POSTGRES_DB: 'codimd'
      POSTGRES_PASSWORD: 'mypwd'
      POSTGRES_USER: 'codimd'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'codimd']
    labels:
      traefik.enable: false
    networks:
      - 'codi-internal'
    restart: 'always'
    volumes:
      - './db:/var/lib/postgresql/data'
